In [ ]:
Numpy
convert A list,tuple,dict in to Numpy array
How to generate array with in a range of values
arange
linspace
random.randint
basic arthimetc operators on numpy array

In [5]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# How to slicing
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
# Fancy Indexing or Boolean Indexing
print(a[a>5])

[6 7 8 9]


In [9]:
a.shape

(10,)

In [10]:
a.ndim

1

In [11]:
a2 = np.random.randint(10,30,(3,3))
a2

array([[11, 19, 27],
       [27, 12, 20],
       [19, 18, 28]])

In [12]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [13]:
for i in a2:
    print(i)
    break

[11 19 27]


In [14]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()

11 19 27 
27 12 20 
19 18 28 


In [15]:
print(a2[0],type(a2[0]),a2[0].shape)

[11 19 27] <class 'numpy.ndarray'> (3,)


In [16]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[27 12 20]
 [19 18 28]] <class 'numpy.ndarray'> (2, 3)


In [17]:
# rows from 0  to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

20
20


In [18]:
print(a2[1:3])

[[27 12 20]
 [19 18 28]]


In [19]:
print(a2[1:3,0:2])

[[27 12]
 [19 18]]


In [20]:
print(a2)

[[11 19 27]
 [27 12 20]
 [19 18 28]]


In [21]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[39, 25, 26],
        [55, 38, 33],
        [48, 49, 14],
        [53, 77, 62],
        [17, 54, 99]],

       [[15, 73, 76],
        [73, 92, 24],
        [20, 62, 41],
        [67, 76, 16],
        [26, 27, 21]],

       [[69, 66, 47],
        [14, 56, 32],
        [53, 71, 86],
        [92, 33, 77],
        [90, 80, 86]],

       [[94, 38, 97],
        [70, 96, 86],
        [65, 37, 91],
        [86, 97, 52],
        [72, 76, 76]],

       [[20, 36, 59],
        [68, 74, 47],
        [84, 32, 55],
        [53, 31, 49],
        [61, 64, 39]]])

In [22]:
print(a3[:2]) # indices - 0,1

[[[39 25 26]
  [55 38 33]
  [48 49 14]
  [53 77 62]
  [17 54 99]]

 [[15 73 76]
  [73 92 24]
  [20 62 41]
  [67 76 16]
  [26 27 21]]]


In [23]:
print(a3[1::2])

[[[15 73 76]
  [73 92 24]
  [20 62 41]
  [67 76 16]
  [26 27 21]]

 [[94 38 97]
  [70 96 86]
  [65 37 91]
  [86 97 52]
  [72 76 76]]]


In [24]:
print(a3[1::2,2])

[[20 62 41]
 [65 37 91]]


In [25]:
print(a3[1::2,0:5:2])

[[[15 73 76]
  [20 62 41]
  [26 27 21]]

 [[94 38 97]
  [65 37 91]
  [72 76 76]]]


In [26]:
print(a3[1::2,0:5:2,2])

[[76 41 21]
 [97 91 76]]


In [27]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False,  True]],

       [[False, False, False],
        [False, False,  True],
        [False, False, False],
        [ True, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [28]:
# Boolean Indexing
a3[a3==86]

array([86, 86, 86, 86])

In [29]:
a3[a3>50]

array([55, 53, 77, 62, 54, 99, 73, 76, 73, 92, 62, 67, 76, 69, 66, 56, 53,
       71, 86, 92, 77, 90, 80, 86, 94, 97, 70, 96, 86, 65, 91, 86, 97, 52,
       72, 76, 76, 59, 68, 74, 84, 55, 53, 61, 64])

In [30]:
a3[(a3>50) & (a3<70)] #or -- |

array([55, 53, 62, 54, 62, 67, 69, 66, 56, 53, 65, 52, 59, 68, 55, 53, 61,
       64])

In [31]:
a3[(a3<50) | (a3>70)]

array([39, 25, 26, 38, 33, 48, 49, 14, 77, 17, 99, 15, 73, 76, 73, 92, 24,
       20, 41, 76, 16, 26, 27, 21, 47, 14, 32, 71, 86, 92, 33, 77, 90, 80,
       86, 94, 38, 97, 96, 86, 37, 91, 86, 97, 72, 76, 76, 20, 36, 74, 47,
       84, 32, 31, 49, 39])

In [32]:

L = list(range(100))
# 0,1,2,3--- L[:]
# 1,2,3,4.... L[1:]
# 1,3,5,7,9,11,13 #L[1::2]
# 1,13,45,74,23,67 #

In [33]:
L[[1,13,45,74,23,67]]

TypeError: list indices must be integers or slices, not list

In [34]:
aL = np.array(L)
aL[[1,13,45,74,23,67]]

array([ 1, 13, 45, 74, 23, 67])

In [35]:
aL[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [36]:
a2

array([[11, 19, 27],
       [27, 12, 20],
       [19, 18, 28]])

In [37]:
a2[[1,2],[0,1]] # (1,0)(2,1)

array([27, 18])

In [38]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])

[92 86]
92
86


In [ ]:
statistical Functions

In [40]:
a = np.random.randint(20,30,5)
a

array([21, 28, 25, 27, 26])

In [41]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

25.4
25.4


In [42]:
# sorted a [23,24,25,27,29]
np.median(a)

26.0

In [43]:
print(np.quantile(a,0.25)) # Q1
print(np.quantile(a,0.5)) # Q2
print(np.quantile(a,0.75)) # Q3

25.0
26.0
27.0


In [ ]:
Logorithemic and Exponential

In [45]:
import numpy as np
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [46]:

print(np.log2(2))
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [1]:
#np.log(0)
#np.log2(0)
# np.log10(0)

In [2]:
np.log(0+1)

NameError: name 'np' is not defined

In [3]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0)) # np.log(1+0)

NameError: name 'np' is not defined