# Import numpy as np and print the version number.

In [1]:
import numpy as np
np.__version__

'1.15.4'

# Create a 1D array of numbers from 0 to 9

In [2]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


# Create a 3×3 numpy array of all True’s

In [3]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Extract all odd numbers from arr

In [5]:
l=np.arange(20)
print(l)
print(type(l))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [6]:
for i in l:
    if i%2!=0:
        print(i)
    else:
        pass

1
3
5
7
9
11
13
15
17
19


# Replace all odd numbers in arr with -1

In [7]:
for i in l:
    if i%2!=0:
        l[i]=-1
    else:
        pass
print(l)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


# Convert a 1D array to a 2D array with 2 rows¶

In [8]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [9]:
b=np.reshape(a,(2,-1))
print(b)
np.ndim(b)

[[1 2 3 4]
 [5 6 7 8]]


2

# Stack arrays a and b vertically

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
np.hstack(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.hstack(b)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

 # Get the positions where elements of a and b match

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [14]:
for i in range(len(a)):
    if a[i]==b[i]:
        print(i,end=" ")

1 3 5 7 

# Get all items between 5 and 10 from a.

In [15]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)

[ 2  6  1  9 10  3 27]


In [16]:
for i in a:
    if i>5 and i<10:
        print(i)

6
9


# Write a NumPy program to generate five random numbers from the normal distribution

In [17]:
a=np.random.normal(size=5) # from normal distribution 
print(a)

[-0.75957186  0.09743598 -0.50954491  1.05752326  0.42881257]


# Write a NumPy program to generate six random integers between 10 and 30

In [19]:
b=np.random.randint(10,30,size=6)
print(b)

[15 12 20 20 19 29]


# Write a NumPy program to create a 3x3x3 array with random values

In [20]:
x=np.random.random((3,3,3))
print(x)

[[[0.73340655 0.45652138 0.32942757]
  [0.66612188 0.36418886 0.78765162]
  [0.98289565 0.1291213  0.11929222]]

 [[0.37810548 0.73745304 0.52191035]
  [0.23149589 0.30199366 0.00717346]
  [0.63447154 0.72423854 0.5977447 ]]

 [[0.8125311  0.4927543  0.46097736]
  [0.96819662 0.55438513 0.7067668 ]
  [0.78558826 0.72652241 0.48812946]]]


# Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values

In [21]:
s=np.random.random((5,5))
print(s)

[[0.21722639 0.47525091 0.5260638  0.75991485 0.85650176]
 [0.35277667 0.23382352 0.12981748 0.81611722 0.78810518]
 [0.52416464 0.10219685 0.80278131 0.9075733  0.41951914]
 [0.25733858 0.05224748 0.19938274 0.90999717 0.57119467]
 [0.28660671 0.5688163  0.69107628 0.10730808 0.0540855 ]]


In [22]:
np.max(s)

0.9099971737437037

In [23]:
np.min(s)

0.05224748418076486

# Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variables

In [24]:
a=np.random.random((10,4))
print(a)

[[0.96195832 0.86591268 0.469694   0.88127425]
 [0.36522435 0.362428   0.21817086 0.79822392]
 [0.61814157 0.86813447 0.46578623 0.19515906]
 [0.85957576 0.19604833 0.11648069 0.8627631 ]
 [0.43669711 0.98296236 0.45572013 0.87285786]
 [0.89597019 0.03557709 0.19322231 0.96658837]
 [0.73613146 0.40569284 0.0352658  0.70140366]
 [0.11271163 0.57160886 0.71019811 0.18271461]
 [0.38873803 0.25939253 0.63241532 0.40949253]
 [0.32600306 0.91768309 0.95635908 0.01231778]]


In [25]:
h=a[0:5,:]
print(h)

[[0.96195832 0.86591268 0.469694   0.88127425]
 [0.36522435 0.362428   0.21817086 0.79822392]
 [0.61814157 0.86813447 0.46578623 0.19515906]
 [0.85957576 0.19604833 0.11648069 0.8627631 ]
 [0.43669711 0.98296236 0.45572013 0.87285786]]


# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)

In [26]:
x = np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[3 8 1 2 7 0 6 4 5 9]


# Read an JPEG image into a numpy array, return the size and shap of that image

In [27]:
from PIL import Image # pillow module
from numpy import asarray # converting image to array
image = Image.open('kolala.jpg')
data = asarray(image)
print(type(data))
print(data.shape)
print(data.size)

FileNotFoundError: [Errno 2] No such file or directory: 'kolala.jpg'

In [ ]:
Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# swap columns 1 and 2 in the array arr.

In [30]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


# How to reverse the rows of a 2D array?

In [31]:
arr = np.arange(9).reshape(3,3)
print(arr)
np.flip(arr,axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# Reverse the columns of a 2D array arr.

In [32]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])